### ISSUE TITLE
Webpack error

### ISSUE THREAD

**Issue by NicholasJacques** [turingschool-examples/jwt-tutorial#1]
I'm getting an error related to the css file when I run `npm start`
Spent awhile troubleshooting/googling but came up empty.
Haven't made any changes to src/app.css
using node v8.1.2

```
ERROR in ./src/app.css
Module parse failed: /Users/nicholasjacques/turing/4module/classwork/jwt-tutorial/src/app.css Unexpected token (1:6)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (1:6)
    at Parser.pp$4.raise (/Users/nicholasjacques/turing/4module/classwork/jwt-tutorial/node_modules/webpack/node_modules/acorn/dist/acorn.js:2221:15)
    at Parser.pp.unexpected (/Users/nicholasjacques/turing/4module/classwork/jwt-tutorial/node_modules/webpack/node_modules/acorn/dist/acorn.js:603:10)
    at Parser.pp.semicolon (/Users/nicholasjacques/turing/4module/classwork/jwt-tutorial/node_modules/webpack/node_modules/acorn/dist/acorn.js:581:61)
    at Parser.pp$1.parseExpressionStatement (/Users/nicholasjacques/turing/4module/classwork/jwt-tutorial/node_modules/webpack/node_modules/acorn/dist/acorn.js:966:10)
    at Parser.pp$1.parseStatement (/Users/nicholasjacques/turing/4module/classwork/jwt-tutorial/node_modules/webpack/node_modules/acorn/dist/acorn.js:730:24)
    at Parser.pp$1.parseTopLevel (/Users/nicholasjacques/turing/4module/classwork/jwt-tutorial/node_modules/webpack/node_modules/acorn/dist/acorn.js:638:25)
    at Parser.parse (/Users/nicholasjacques/turing/4module/classwork/jwt-tutorial/node_modules/webpack/node_modules/acorn/dist/acorn.js:516:17)
    at Object.parse (/Users/nicholasjacques/turing/4module/classwork/jwt-tutorial/node_modules/webpack/node_modules/acorn/dist/acorn.js:3098:39)
    at Parser.parse (/Users/nicholasjacques/turing/4module/classwork/jwt-tutorial/node_modules/webpack/lib/Parser.js:902:15)
    at NormalModule.<anonymous> (/Users/nicholasjacques/turing/4module/classwork/jwt-tutorial/node_modules/webpack/lib/NormalModule.js:104:16)
 @ ./src/app.js 29:0-20

```

**Comment by NicholasJacques** [comment]
Attempted to run it on a fresh clone with node v6.9.5 (confirmed working version) and got the same error.
